name: PHPUnit Tests

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --env MYSQL_ROOT_PASSWORD=root --env MYSQL_DATABASE=testdb
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: |
        composer install

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h 127.0.0.1 -P 3306 -u root -proot -e 'select 1'; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Run PHPUnit tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: testdb
        DB_USER: root
        DB_PASSWORD: root
      run: vendor/bin/phpunit
