name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: tp02_devops
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=30s --health-interval=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Create .env.testing file
        run: |
          echo "CI_ENVIRONMENT=testing" >> .env.testing
          echo "database.default.hostname=127.0.0.1" >> .env.testing
          echo "database.default.database=tp02_devops" >> .env.testing
          echo "database.default.username=${{ env.DB_USERNAME }}" >> .env.testing
          echo "database.default.password=${{ env.DB_PASSWORD }}" >> .env.testing
          echo "database.default.DBDriver=MySQLi" >> .env.testing
          echo "database.default.port=3306" >> .env.testing

      - name: Run migrations
        run: php spark migrate

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/codeigniter4/framework/system/Test/bootstrap.php tests/Models/FactureModelTest.php
