name: CI

on:
  push:
    branches:
      - master  # Change 'main' to 'master'
  pull_request:
    branches:
      - master  # Change 'main' to 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Update to PHP 8.1 or higher

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
